
//0
//9
//115
//131
//BETA 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Reflection;

[assembly: AssemblyVersion("0.9.115")]
[assembly: AssemblyFileVersion("0.9.115.131")]
[assembly: AssemblyInformationalVersion("0.9.115-BETA")]