
//0
//9
//163
//64235
//BETA 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Reflection;

[assembly: AssemblyVersion("0.9.163")]
[assembly: AssemblyFileVersion("0.9.163.64235")]
[assembly: AssemblyInformationalVersion("0.9.163-BETA")]