
//0
//9
//166
//22299
//BETA 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
  
using System.Reflection;

[assembly: AssemblyVersion("0.9.165")]
[assembly: AssemblyFileVersion("0.9.165.22299")]
[assembly: AssemblyInformationalVersion("0.9.165-BETA")]